import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { io } from "socket.io-client";

let socket: any;

const Home: NextPage = () => {
  const [input, setInput] = useState<string>("");

  const onChangeHandler = (e: any) => {
    setInput(e.target.value);
    socket.emit("input-change", e.target.value);
  };

  const socketInitializer = async () => {
    await fetch("/api/socket");
    socket = io();

    socket.on("connect", () => {
      console.log("connected");
    });
    socket.on('update-input', (msg: any) => {
      setInput(msg)
    })
  };

  useEffect(() => {
    socketInitializer();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          placeholder="Type something"
          value={input}
          onChange={onChangeHandler}
        />
      </main>
    </>
  );
};
export default Home;
